---
downloads: ~/.ansible-downloads

configure_dock: true
dockitems_remove:
- Launchpad
- TV
- Podcasts
- Messages
- Mail
- Maps
- Photos
- FaceTime
- Calendar
- Contacts
- Reminders
- Music
- News
- App Store
dockitems_persist:
- name: Brave Browser
  path: "/Applications/Brave Browser.app"
  position: 1
- name: Binance
  path: "/Applications/Binance.app"
  position: 2

homebrew_installed_packages:
  - azure-cli
  - base64
  - bash
  - bat
  - chezmoi
  - exa
  - fd
  - fish
  - fzf
  - gnu-sed
  - gnupg
  - gopass
  - gopass-jsonapi
  - htop
  - jq
  - kubernetes-cli
  - kubie
  # - neovim
  - pinentry-mac
  - tmux
  
homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - binance
  - brave-browser
  - caffeine
  - homebrew/cask-versions/firefox-developer-edition
  - google-chrome
  - kitty
  - homebrew/cask-fonts/font-fira-code
  - homebrew/cask-fonts/font-fira-code-nerd-font
  - homebrew/cask-fonts/font-sauce-code-pro-nerd-font
  - homebrew/cask-fonts/font-monoid
  - homebrew/cask-fonts/font-monoid-nerd-font
  # - homebrew/cask-fonts/font-source-code-pro-for-powerline
  - visual-studio-code
  - the-unarchiver

visual_studio_code_extensions:
  - arcticicestudio.nord-visual-studio-code
  - dbaeumer.vscode-eslint
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - golang.go
  - hashicorp.terraform
  - vscodevim.vim
  - eamodio.gitlens
  - ms-vscode.azurecli
  - vscode-icons-team.vscode-icons
  - ms-vscode.powershell
  - coenraads.bracket-pair-colorizer-2
  - davidanson.vscode-markdownlint
  - alefragnani.project-manager
  - ms-azure-devops.azure-pipelines