---
- name: Disable the "Are you sure you want to open this application?" dialog
  ansible.builtin.command: defaults write com.apple.LaunchServices LSQuarantine -bool false

- name: Restart automatically if the computer freezes
  become: yes
  become_flags: '-E'
  become_method: sudo
  ansible.builtin.command: systemsetup -setrestartfreeze on
  changed_when: false

- name: Finder - show status bar
  ansible.builtin.command: defaults write com.apple.finder ShowStatusBar -bool true


- name: Finder - show path bar
  ansible.builtin.command: defaults write com.apple.finder ShowPathbar -bool true
#   when: pathbar | bool == false

- name: Finder - display full POSIX path
  ansible.builtin.command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

- name: Finder - keep folders on top
  ansible.builtin.command: defaults write com.apple.finder _FXSortFoldersFirst -bool true

- name: Finder - search current folder by default
  ansible.builtin.command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

- name: Finder - disable file extension change warning
  ansible.builtin.command: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

- name: Avoid writing .DS_Store to network
  ansible.builtin.command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: Avoid writing .DS_Store to USB
  ansible.builtin.command: defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

- name: Set dock icon size
  ansible.builtin.command: defaults write com.apple.dock tilesize -int 32

- name: Don't show recent apps in dock
  ansible.builtin.command: defaults write com.apple.dock show-recents -bool false

- name: Prevent time machine from prompting to use new hard drives as backup
  ansible.builtin.command: defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

- name: Expand save panel by default
  ansible.builtin.command: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

- name: Expand print panel by default
  ansible.builtin.command: defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true

- name: Automatically close printer app once print has completed
  ansible.builtin.command: defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

- name: Save screenshots as PNG
  ansible.builtin.command: defaults write com.apple.screencapture type -string "png"

- name: Disable shaddow in screenshots
  ansible.builtin.command: defaults write com.apple.screencapture disable-shadow -bool true

