---
- name: Install fisher
  shell: fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"

- name: Install fisherman plugins
  shell: fish -c "fisher install {{ item }}"
  loop:
    - ilancosman/tide
    - rstacruz/fish-asdf
    - gazorby/fish-exa
    - PatrickF1/fzf.fish
    - jhillyerd/plugin-git

- name: Set default shell
  become: yes
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/local/bin/fish
