---
- name: Install fish
  community.general.homebrew:
    name: fish
    state: present

- name: Install fisher
  shell: fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"

- name: Install fisherman plugins
  shell: fish -c "fisher install {{ item }}"
  loop:
    - ilancosman/tide
    - rstacruz/fish-asdf
    - gazorby/fish-exa
    - PatrickF1/fzf.fish
    - jhillyerd/plugin-git
    - danhper/fish-ssh-agent
    - laughedelic/pisces
    - jethrokuan/z

- name: Copy config.fish
  copy:
    src: config.fish
    dest: "{{ lookup('env', 'HOME') }}/.config/fish/config.fish"

- name: Set default shell
  become: yes
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/local/bin/fish
